# -*- coding: utf-8 -*-
"""11047.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uk6DixVpzxCulNZ6ote_oSlkfgGh_ZcB
"""

n, k = map(int, input().split())
vals = []
result = 0

for i in range(n):
  val = int(input())
  vals.append(val)

vals.reverse()

for j in vals:
  if k // j == 0:
    continue
  else:
    continue

