# -*- coding: utf-8 -*-
"""백준_2839.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kf1q-uX9mpT_C6H7j0RzOMZ8NQdsIVeE
"""

n = int(input())
result = 0


if n % 5 == 0 or (n % 5) % 3==0:
  result += int(n//5 + (n%5)/3)
elif n % 3 == 0:
  result += n//3
else:
  result = -1

print(result)

n = int(input())
result = 0

while n != 0:
  if n >= 5:
    n -= 5
    result += 1
    while n % 3 == 0:
      n -= 3
      result += 1
      if n == 0:
        break
    if n == 1 or n == 2:
      result == 1
  else:
    n -= 3
    result += 1
    if n == 1 or n == 2:
      result == 1

print(result)

n = int(input())

result = 0
while n >= 0 :
    if n % 5 == 0 :  # 5의 배수이면
        result += (n // 5)  # 5로 나눈 몫을 구해야 정수가 됨
        print(result)
        break
    n -= 3  
    result += 1  # 5의 배수가 될 때까지 설탕-3, 봉지+1
else :
    print(-1)

