# -*- coding: utf-8 -*-
"""백준_1931.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4Lr6TfIGcal6N7x5CRJP6sVfWa9mjh6
"""

n = int(input())
time = []
for i in range(n):
  start, end = map(int, input().split())
  time.append((start, end))

time.sort(key = lambda x: (x[1], x[0]))
count = 1

end_time = time[0][1]
for i in range(1, n):
  if end_time <= time[i][0]:
    count += 1
    end_time = time[i][1]
print(count)