# -*- coding: utf-8 -*-
"""백준_1541.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb-If3-oWHesGqBoV27-fI6NuwAtnszT
"""

n = input().split('-')
result = 0
for i in n[0].split('+'):
  result += int(i)

for i in n[1:]:
  for j in i.split('+'):
    # 이미 -를 기준으로 나뉘었기 때문에 +를 가지고 있는 원소의 가장 앞 숫자는 빼줘야함
    # ()를 풀면 -에 의해 +가 -로 바뀐다는 걸 생각하자
    result -= int(j)
print(result)