# -*- coding: utf-8 -*-
"""백준_1026.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NpIkOpPKqaKqUkbVD0rk-OP0we5ImwEM
"""

n = int(input())

a = list(map(int, input().split()))
b = list(map(int, input().split()))

result = 0
for x, y in zip(sorted(a, reverse=True), sorted(b)):
  result += x*y

print(result)

