# -*- coding: utf-8 -*-
"""백준_단계별_문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIU7WhnghBVoZikvClpAu7Wvracd_Lxs
"""

# 1152
words = input().split()
print(len(words))

# 2908
a, b = input().split()
a, b = list(a), list(b)
a.reverse()
a = int(''.join(a))
b.reverse()
b = int(''.join(b))

if a > b:
  print(a)
else:
  print(b)

# 100, 10 으로 나눠서 백의 자리, 십의 자리, 일의 자리 숫자를 뒤집어 더해주는 방법도 있음

# 5622
word = input()
answer = 0
for i in word:
  if i == 'A' or i == 'B' or i == 'C':
    answer += 3
  elif i == 'D' or i == 'E' or i == 'F':
    answer += 4
  elif i == 'G' or i == 'H' or i == 'I':
    answer += 5
  elif i == 'J' or i == 'K' or i == 'L':
    answer += 6
  elif i == 'M' or i == 'N' or i == 'O':
    answer += 7
  elif i == 'P' or i == 'Q' or i == 'R' or i == 'S':
    answer += 8
  elif i == 'T' or i == 'U' or i == 'V':
    answer += 9
  elif i == 'W' or i == 'X' or i == 'Y' or i == 'Z':
    answer += 10

print(answer)

word = input()
time = {'ABC': 3, 'DEF': 4, 'GHI': 5, 'JKL': 6, 'MNO': 7, 'PQRS': 8, 'TUV': 9, 'WXYZ': 10}
result = 0
for i in time:
  for j in word:
    if j in i:
      result += time[i]

print(result)

input_ = input()
words = ['c=', 'c-', 'dz=', 'd-', 'lj', 'nj', 's=', 'z=']
result = 0

for i in words:
  if i in input_:
    result += input_.count(i)
    input_ = input_.replace(i, "") #nljj에서 lj를 생략하면 nj가 되어버려서 words의 nj랑 일치하게 됨..

result += len(list(input_))

print(result)

input_ = input()
words = ['c=', 'c-', 'dz=', 'd-', 'lj', 'nj', 's=', 'z=']
answer = []
result = 0

for i in words:
  if i in input_:
    answer.append(i) # dz=와 z=를 구분 못함..

if 'dz=' in answer:
  answer.pop(answer.index('z='))

for i in answer: 
  input_ = input_.replace(i, '')
  result += 1

result += len(input_)


print(result)

input_ = input()
words = ['c=', 'c-', 'dz=', 'd-', 'lj', 'nj', 's=', 'z=']
result = 0

for i in words:
  if i in input_:
    input_ = input_.replace(i, '#')

print(len(input_))

# 1316
n = int(input())
result = n
for i in range(n):
  word = input()
  for j in range(1, len(word)):
    if word[j-1] == word[j]:
      pass
    elif word[j-1] in word[j:]:
      result -= 1
      break
print(result)

