# -*- coding: utf-8 -*-
"""프로그래머스 구현.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AWfXdRFg4FMDe0P8Q9Dx391AjXFZiv0g
"""

# 프로그래머스 약수
def solution(n):
    answer = [i for i in range(1, n+1) if n % i == 0]
    return sum(answer)

# 서울에서 김서방 찾기
def solution(seoul):
    return "김서방은 {0}에 있다".format(seoul.index("Kim"))

# 문자열 내 p와 y의 개수
def solution(s):
    s = s.lower()
    if s.count('p') == s.count('y'):
        return True
    else:
        return False

# 프로그래머스 체육복
def solution(n, lost, reserve):
    for i in reserve:
        if i in lost:
            lost.pop(lost.index(i))
        elif i-1 in lost:
            lost.pop(lost.index(i-1))
        elif i+1 in lost:
            lost.pop(lost.index(i+1))
    return n - len(lost)