# -*- coding: utf-8 -*-
"""프로그래머스_행렬의 덧셈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rT6w6bmWOA8wf2Av2kv92exPjMD71IhA
"""

def solution(arr1, arr2):
    # 최종 형태는 입력 받은 array와 같을 것이기 때문에 아무 array를 카피해줌
    # array를 카피하지 않고 입력받은 array의 값을 대체하는 방식을 이용해도 됨
    answer = arr1.copy()
    for i in range(len(arr1)):
        for j in range(len(arr1[i])):
            answer[i][j] = arr1[i][j] + arr2[i][j]
    
    return answer