# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tr5BXY7Q8w6xu42TVGefOc6d0wHUGULj
"""

def solution(num):
    if num % 2 == 0:
        answer = "Even"
    else: 
        answer = "Odd"
    return answer

def solution(s):
    return s[len(s)//2] if len(s) % 2 == 1 else s[len(s)//2-1:len(s)//2+1]

def solution(phone_number):
    return '*' * len(phone_number[:-4]) + phone_number[-4:]

def solution(board, moves):
    columns = []
    for i in range(len(board)):
        column = []
        for j in range(len(board)):
            if board[j][i] != 0:
                column.append(board[j][i])
        columns.append(column)

    box = []
    count = 0
    for i in moves:
        if len(columns[i-1]) != 0:
            box.append(columns[i-1].pop(0))
            if len(box) >= 2:
                if box[-1] == box[-2]:
                    box.pop()
                    box.pop()
                    count += 2
        else: 
            continue
    return count

solution([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]],[1,5,3,5,1,2,1,4])

