# -*- coding: utf-8 -*-
"""백준_12873.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kgBiaKEzonggH8RobTE-fgMWPF9eyAzo
"""

n = int(input())
num_list = list(range(1, n+1))
# for i in num_list:
#   if len(num_list) > 1:
#     num_list.pop((i+1)**3 % len(num_list))
#   else: 
#     break

i = 1
while len(num_list) > 1:
  # 제외된 후 시계 방향으로 다음 사람에게 이동하는 경우 반영해야됨
  index = i**3 % len(num_list) + len(num_list[:num_list[i**3 % len(num_list)]])
  if i == 1:
    num_list.pop(i**3 % len(num_list))
  elif index > len(num_list):
    num_list.pop(index % 6 - 1)
  else: 
    num_list.pop(index)
  i += 1
print(num_list[0], num_list)

# 큐 이용하기