# -*- coding: utf-8 -*-
"""DFS와 BFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YRohOojL-MEo1zTQdc4qZdypYSfj-pL6
"""

n, m, v = map(int, input().split())

graph = [[] for i in range(n)]

for i in range(m):
  node, next = map(int, input().split())
  graph[node].append(next)

def dfs(graph, v, visited):
  visited[v] = True
  print(v, end='')
  for j in graph[v]:
    if not visited[j]:
      dfs(graph, i, visited)

visited = [False] * (n+1)

dfs(graph, v, visited)